import Phaser from 'phaser';

/** All audio keys → files. Loaded by BootScene, played through this module. */
export const AUDIO: Record<string, string> = {
  // per-scene tracks, generated by the author to match each moment
  'music/prologue': 'assets/audio/music/prologue.mp3',
  'music/checkup': 'assets/audio/music/checkup.mp3',
  'music/waters': 'assets/audio/music/waters.mp3',
  'music/delivery': 'assets/audio/music/delivery.mp3',
  'music/corridor': 'assets/audio/music/corridor.mp3',
  'music/nicu': 'assets/audio/music/nicu.mp3',
  'music/ward': 'assets/audio/music/ward.mp3',
  'music/ending': 'assets/audio/music/ending.mp3',
  'sfx/beep': 'assets/audio/sfx/beep.ogg',
  'sfx/monitor': 'assets/audio/sfx/monitor.wav',
  'sfx/blip': 'assets/audio/sfx/blip.wav',
  'sfx/step-wood': 'assets/audio/sfx/step-wood.wav',
  'sfx/step-tile': 'assets/audio/sfx/step-tile.wav',
  'sfx/heartbeat': 'assets/audio/sfx/heartbeat.wav',
  'sfx/door-close': 'assets/audio/sfx/door-close.ogg',
  'sfx/door-slam': 'assets/audio/sfx/door-slam.ogg',
  'sfx/switch': 'assets/audio/sfx/switch.ogg',
  'sfx/paper': 'assets/audio/sfx/paper.ogg',
};

/** Thin global mixer: one ambience, one music, fire-and-forget SFX,
 *  and the CTG monitor beep loop. Survives scene restarts. */
class Audio {
  private game?: Phaser.Game;
  private ambience?: Phaser.Sound.BaseSound;
  private music?: Phaser.Sound.BaseSound;
  private beepTimer?: number;

  attach(game: Phaser.Game): void {
    this.game = game;
  }

  private get sound(): Phaser.Sound.BaseSoundManager | undefined {
    return this.game?.sound;
  }

  /** Play (or crossfade to) a looping room tone. */
  setAmbience(key: string | null, volume = 0.2): void {
    const snd = this.sound;
    if (!snd) return;
    if (this.ambience?.key === key) {
      return; // same room tone continues across scene restarts
    }
    this.ambience?.destroy();
    this.ambience = undefined;
    if (key) {
      this.ambience = snd.add(key, { loop: true, volume });
      this.whenUnlocked(() => this.ambience?.play());
    }
  }

  private musicRate = 1;

  /** Start music if not already playing this key. `rate` 0.5 = an octave
   *  down — the corridor plays the game's own theme slowed into a drone. */
  setMusic(key: string | null, volume = 0.3, rate = 1): void {
    const snd = this.sound;
    if (!snd) return;
    if (this.music?.key === key && this.musicRate === rate) {
      (this.music as Phaser.Sound.WebAudioSound).setVolume(volume);
      return;
    }
    this.music?.destroy();
    this.music = undefined;
    this.musicRate = rate;
    if (key) {
      this.music = snd.add(key, { loop: true, volume, rate });
      this.whenUnlocked(() => this.music?.play());
    }
  }

  /** SFX sit UNDER the music, always: everything routes through this bus. */
  private static readonly SFX_BUS = 0.5;

  sfx(key: string, opts: { volume?: number; rate?: number } = {}): void {
    this.sound?.play(key, {
      volume: (opts.volume ?? 0.5) * Audio.SFX_BUS,
      rate: opts.rate ?? 1,
    });
  }

  /** The CTG monitor: a soft beep every 1.1s. It slowly becomes the music. */
  startBeep(volume = 0.12): void {
    this.stopBeep();
    this.beepTimer = window.setInterval(() => {
      this.sfx('sfx/monitor', { volume });
    }, 1100);
  }

  stopBeep(): void {
    if (this.beepTimer !== undefined) {
      window.clearInterval(this.beepTimer);
      this.beepTimer = undefined;
    }
  }

  private layer?: Phaser.Sound.BaseSound;

  /** Extra looping mood layer on top of ambience+music (e.g. a heartbeat). */
  setLayer(key: string | null, volume = 0.15): void {
    const snd = this.sound;
    if (!snd) return;
    if (this.layer?.key === key) {
      (this.layer as Phaser.Sound.WebAudioSound).setVolume(volume);
      return;
    }
    this.layer?.destroy();
    this.layer = undefined;
    if (key) {
      this.layer = snd.add(key, { loop: true, volume });
      this.whenUnlocked(() => this.layer?.play());
    }
  }

  /** Silence everything at once — the birth beat. */
  allStop(): void {
    this.stopBeep();
    this.ambience?.destroy();
    this.ambience = undefined;
    this.music?.destroy();
    this.music = undefined;
    this.layer?.destroy();
    this.layer = undefined;
  }

  private whenUnlocked(fn: () => void): void {
    const snd = this.sound;
    if (!snd) return;
    if (snd.locked) {
      snd.once(Phaser.Sound.Events.UNLOCKED, fn);
    } else {
      fn();
    }
  }
}

export const audio = new Audio();
