#!/usr/bin/env python3
"""Pack labeled crops into public/assets/sprites and emit src/data/assetIndex.ts."""

import json
from pathlib import Path

from PIL import Image

ROOT = Path(__file__).resolve().parent.parent
OUT = ROOT / "public" / "assets" / "sprites"
LABELS = sorted((ROOT / "tools" / "labels").glob("*.json"))

index: dict[str, str] = {}
for label_path in LABELS:
    spec = json.loads(label_path.read_text())
    src = ROOT / spec["src"]
    default_scale = spec.get("default_scale", 0.25)
    scales = spec.get("scales", {})
    for crop, names in spec["items"].items():
        if isinstance(names, str):
            names = [names]
        img = Image.open(src / f"{crop}.png")
        scale = scales.get(crop, default_scale)
        w, h = max(1, round(img.width * scale)), max(1, round(img.height * scale))
        small = img.resize((w, h), Image.NEAREST)
        for name in names:
            dest = OUT / f"{name}.png"
            dest.parent.mkdir(parents=True, exist_ok=True)
            small.save(dest)
            if name in index:
                raise SystemExit(f"duplicate logical name: {name}")
            index[name] = f"assets/sprites/{name}.png"

# Mirrored frames: AI sheets often face one way only; "flips" derives the
# other side. {"player/idle-left": "player/idle-right"} mirrors right → left.
for label_path in LABELS:
    spec = json.loads(label_path.read_text())
    for name, source in spec.get("flips", {}).items():
        src_png = OUT / f"{source}.png"
        img = Image.open(src_png).transpose(Image.FLIP_LEFT_RIGHT)
        dest = OUT / f"{name}.png"
        dest.parent.mkdir(parents=True, exist_ok=True)
        img.save(dest)
        if name in index:
            raise SystemExit(f"duplicate logical name: {name}")
        index[name] = f"assets/sprites/{name}.png"

# Index everything under sprites/ — including files other tools (placeholders.py)
# or the user dropped in by hand.
for png in OUT.rglob("*.png"):
    name = str(png.relative_to(OUT).with_suffix(""))
    index.setdefault(name, f"assets/sprites/{name}.png")

ts = ["// AUTO-GENERATED by tools/pack.py — do not edit by hand.",
      "export const ASSETS: Record<string, string> = {"]
for name in sorted(index):
    ts.append(f"  '{name}': '{index[name]}',")
ts.append("};")
(ROOT / "src" / "data" / "assetIndex.ts").parent.mkdir(parents=True, exist_ok=True)
(ROOT / "src" / "data" / "assetIndex.ts").write_text("\n".join(ts) + "\n")
print(f"packed {len(index)} sprites from {len(LABELS)} label files")
